### ISSUE TITLE
[FIX] AI conclusion card could cover `view latter` button

### ISSUE THREAD

**Issue by Dynesshely** [gaogaotiantian/biliscope#137] opened 2024-02-06 11:04 UTC
Screen shot:

![image](https://github.com/gaogaotiantian/biliscope/assets/50760269/2cc3b2ee-a03c-4751-9215-f5ff6d7e3d88)

**Comment by gaogaotiantian** [comment] 2024-02-07 02:40
Fact, but not a bug :)

Most of the time that button will not be covered (even if you directly try to click that button). The button is only shielded when your cursor stay at some specific positions.

The button is not that frequently used and it's only hidden in some corner cases, so I'll just close this.

**Closed by gaogaotiantian** 2024-02-07 02:40 UTC

**Comment by Dynesshely** [comment] 2024-02-08 18:53
I know it's not a bug, I just think small details like this would make the project better.

If you are willing to tell me the location of the code related to setting position of the AI summary card, I'd be happy to help add the code to avoid obscuring the button.

If you think this function is not necessary, it is ok :)

**Comment by gaogaotiantian** [comment] 2024-02-08 19:32
Thank you for the suggestion. However, I don't believe this specific feature will make the product better for the following reasons:
1. Where would you put the card?
    * Move it away from the button - inconsistent behavior for the relative position between the cursor and the card, the user may feel a bit off
    * Move it under the button - the button will appear on the card and be separated from the video, also weird.
2. It will make the code unnecessarily complicated.
    * It's not trivial to just "avoid" the button. You need to calculate whether it's the best to be on left/right/top/bottom of it. What if after the adjustment, it's out of the screen? You need extra logic to deal with that. It's not impossible, but it would make the code hard to maintain.

All the features cost, that's a fact for any product. However, this improvement is not worth the cost. And to be honest, at least from my personal perspective, even without the concern for the cost, I don't think it's a better experience - I would rather make it consistent.

**Comment by Dynesshely** [comment] 2024-02-09 07:13
You're right on this problem. It's indeed too many problems to consider.

By the way, I have another idea.
I will post my thoughts in a new issue after sorting out my thoughts.

**Comment by F-park** [comment] 2024-08-07 07:11
I fix it in #206 , can you help me test it?
